name: courses
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.9
  simple_circular_progress_bar: ^1.0.2
  percent_indicator: ^4.2.3
  group_radio_button: ^1.3.0
  flutter_localization: ^0.2.0
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.4
  flutter_lints: ^3.0.1
  mask_text_input_formatter: ^2.7.0
  pinput: ^3.0.1
  google_fonts: ^6.1.0
  dropdown_button2: ^2.3.9

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/
    - assets/images/



