import 'package:flutter_translate/flutter_translate.dart';


final languages = [
  'uz',
  'ru',
];


extension ExtStr on String {
  String get tr {
    return translate(this);
  }
}

String authorName  = "author_name" ;
String learnFromProf =  "learn_from_prof";
String basic =  "basic";
String learnSale =  "learn_sale";
String loremIpsum =  "lorem_ipsum";
String ourCourses =  "our_courses";
String bestSeller =  "best_seller";
String anonymousCall =  "anonymous_call";
String price =  "price";
String platformOffer =  "platform_offer";
String profile =  "profile";
String aboutCourse =  "about_course";
String courseContent =  "course_content";
String courseThemes =  "course_themes";
String advantagesAndRequirements =  "advantages_and_requirements";
String firstLesson =  "first_lesson";
String secondLesson =  "second_lesson";
String thirdLesson =  "third_lesson";
String forthLesson =  "forth_lesson";
String numberLesson =  "number_lesson";
String buy =  "buy";
String advantages =  "advantages";
String easyAndGood =  "easy_and_good";
String designAndCode =  "design_and_code";
String explainedAndComprehensive =  "explained_and_comprehensive";
String requirements =  "requirements";
String incomingOutgoingCalls =  "incoming_outgoing_calls";
String clientTraining =  "client_training";
String courseGoals =  "course_goals";
String operatorResponsibility =  "operator_responsibility";
String informationAboutOrganization =  "information_about_organization";
String informationAboutProduct =  "information_about_product";
String workingWithClients =  "working_with_clients";
String downloadWrittenVer =  "download_written_ver";
String nameClient =  "name_client";
String datePosted =  "date_posted";
String description =  "description";
String comments =  "comments";
String comment =  "comment";
String enter =  "enter";
String buyCourse =  "buy_course";
String commentNotFound =  "comment_not_found";
String loremIps =  "lorem_ips";
String enteringSystem =  "entering_system";
String phoneNumber =  "phone_number";
String register =  "register";
String keep =  "keep";
String fullName =  "full_name";
String enterName =  "enter_name";
String smsSent =  "sms_sent";
String password =  "password";
String enterCode =  "enter_code";
String cameCode =  "came_code";
String timer =  "timer";
String resent =  "resent";
String yourAction =  "your_action";
String faq =  "faq";
String estimateProgram =  "estimate_program";
String aboutUs =  "about_us";
String myCourses =  "my_courses";
String editInfo =  "edit_info";
String changePassword =  "change_password";
String save =  "save";
String cancel =  "cancel";
String oldPassword =  "old_password";
String newPassword =  "new_password";
String repeatNewPassword =  "repeat_new_password";
String successPassword =  "success_password";
String test =  "test";
String startTest =  "start_test";
String contentStartTest =  "content_start_test";
String fail =  "fail";
String countQuestions =  "count_questions";
String rightAnswer =  "right_answer";
String retry =  "retry";
String chooseFormat =  "choose_format";
String chooseSpeed =  "choose_speed";

//auth and splash
// String enter = 'enter';
// String enterPhone = 'enter_phone';
// String editPhone = 'edit_phone';
// String smsSended = 'sms_sended';
// String resend = 'resend';
// String userInfo = 'user_info';
// String userName = 'name';
// String userSurname = 'surname';
// String you = 'you';
// String man = 'man';
// String woman = 'woman';
// String bornDate = 'born_date';
// String selectDate = 'select_date';
// String save = 'save';
// String enterName = 'enter_name';
// String enterSurname = 'enter_surname';
// String cancel = 'cancel';
// String error = 'error';
// String setOrder = 'set_order';
// String editInfo = 'edit_info';
// String language = 'language';
// String lanKey = 'lan_key';
// String selectLanguage = 'select_language';
// String about = 'about';
// String faq = 'faq';
// String night = 'night';
// String exit = 'exit';
// String permitLocation = 'permit_location';
// String workWell = 'work_well';
// String yourLocation = 'your_location';
// String finalLocation = 'final_location';
// String setWhere = 'set_where';
// String setWhereGo = 'set_where_go';
// String writeComment = 'write_comment';
// String comment = 'comment';
// String ratingDriver = 'rating_driver';
// String orderCompleted = 'order_completed';
// String back = 'back';
// String newMessage = 'new_message';
// String cancelOrder = 'cancel_order';
// String sureCancel = 'sure_cancel';
// String wait = 'wait';
// String total = 'total';
// String dispacher = 'dispacher';
// String comfirm = 'comfirm';
// String saved = 'saved';
// String myOrders = 'my_orders';
// String thisOrder = 'this_order';
// String callOperator = 'call_operator';
// String almost = 'almost';
// String sameTime = 'same_time';
// String atTheAddress = 'at_the_address';
// String arrivingTime = 'arriving_time';
// String selectMap = 'select_map';
// String skip = 'skip';
// String call = 'call';
// String payBonus = 'pay_bonus';
// String yes = 'yes';
// String no = 'no';
// String ok = 'ok';
// String bonusHistory = 'bonus_history';
// String sureExit = 'sure_exit';
// String noConnection = 'no_connection';
// String checkConnection = 'check_connection';
// String madedBy = 'maded_by';
// String telegram = 'telegram';
// String supportNum = 'support_num';
// String appVersion = 'app_version';
// String delAccount = 'del_account';
// String waitCar = 'wait_car';
